---

default: &default
  adapter: postgresql
  encoding: unicode
  username: annual_leave
  password: annual_leave
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: annual_leave_development

test:
  <<: *default
  database: annual_leave_test

production:
  <<: *default
  database: annual_leave_production
  username: annual_leave
  password: <%= ENV["ANNUAL_LEAVE_DATABASE_PASSWORD"] %>
